-- 创建养宠贴士表
CREATE TABLE IF NOT EXISTS pet_tips (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(200) NOT NULL COMMENT '贴士标题',
    category VARCHAR(50) NOT NULL COMMENT '分类',
    content TEXT NOT NULL COMMENT '贴士内容',
    cover_image VARCHAR(500) COMMENT '封面图片',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0 COMMENT '逻辑删除 0-未删除 1-已删除',
    INDEX idx_category (category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='养宠贴士表';
