CREATE TABLE IF NOT EXISTS pet_info (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL COMMENT '宠物名称',
    breed VARCHAR(100) NOT NULL COMMENT '品种',
    age VARCHAR(50) COMMENT '年龄',
    type VARCHAR(50) NOT NULL COMMENT '类型（狗/猫/鸟/其他）',
    gender VARCHAR(20) COMMENT '性别',
    image VARCHAR(500) COMMENT '图片',
    description TEXT COMMENT '描述',
    health_status VARCHAR(100) COMMENT '健康状况',
    status INT DEFAULT 1 COMMENT '状态 0-已领养 1-可领养',
    shelter_id BIGINT COMMENT '救助站ID',
    view_count INT DEFAULT 0 COMMENT '浏览次数',
    story TEXT COMMENT '宠物故事',
    size VARCHAR(50) COMMENT '体型（小型/中型/大型）',
    personality VARCHAR(200) COMMENT '性格特点',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0 COMMENT '逻辑删除 0-未删除 1-已删除',
    INDEX idx_type (type),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='宠物信息表';

CREATE TABLE IF NOT EXISTS pet_adoption (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL COMMENT '用户ID',
    pet_id BIGINT NOT NULL COMMENT '宠物ID',
    status INT DEFAULT 0 COMMENT '状态 0-待审核 1-已通过 2-已拒绝',
    reason TEXT COMMENT '领养原因',
    address VARCHAR(500) COMMENT '居住地址',
    phone VARCHAR(20) COMMENT '联系电话',
    email VARCHAR(100) COMMENT '邮箱',
    applicant_age INT COMMENT '申请人年龄',
    housing_type VARCHAR(100) COMMENT '居住类型',
    has_pet_experience VARCHAR(20) COMMENT '是否有养宠经验',
    family_status TEXT COMMENT '家庭成员情况',
    agree_health_check TINYINT DEFAULT 0 COMMENT '是否同意健康检查',
    agree_neuter TINYINT DEFAULT 0 COMMENT '是否同意绝育',
    agree_good_environment TINYINT DEFAULT 0 COMMENT '是否同意提供良好环境',
    agree_timely_medical TINYINT DEFAULT 0 COMMENT '是否同意及时就医',
    review_note TEXT COMMENT '审核备注',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0 COMMENT '逻辑删除 0-未删除 1-已删除',
    INDEX idx_user_id (user_id),
    INDEX idx_pet_id (pet_id),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='领养申请表';

INSERT INTO pet_info (name, breed, age, type, gender, image, description, health_status, status, view_count, story, size, personality, shelter_id) VALUES
('小黄', '金毛寻回犬', '2岁', '狗', '公', 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=600&q=80', '性格温顺，活泼可爱，喜欢和人玩耍', '健康', 1, 5, '《纸箱里的小火焰》清晨四点的垃圾堆旁，志愿者小陈听见微弱的呜咽。翻动纸箱时，一团姜黄色的毛球滚进他怀里，那是只不足巴掌大的柴犬幼崽，肚皮上还沾着干草。现在这只被取名"栗子"的小狗在救助站已经学会撒欢奔跑。每天清晨它总爱追着扫把跑圆，把拖地的阿姨绕得哭笑不得；午休时分，其他幼犬都趴着打盹，它却顶着漏勺当头盔，在院子里上演独幕剧。兽医说它是见过最皮实的孩子，驱虫疫苗后第二天就活蹦乱跳地扑向新玩具。每当有访客蹲下身，栗子总会歪着脑袋轻咬对方鞋带，尾巴在身后画出半圆。它还不懂什么是永远的家，只知道这个会陪它玩捉迷藏的人类，身上带着和那个寒冷清晨相似的温暖气息。', '大型', '活泼', 1),
('露娜', '波斯猫', '6个月', '猫', '母', 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=600&q=80', '温柔优雅，喜欢安静的环境', '健康', 1, 3, '《窗边的小公主》露娜是在一个雨夜被发现的，它蜷缩在公寓楼下的纸箱里，浑身湿透。现在的露娜已经是救助站的小公主了，每天最爱趴在窗台上看外面的风景。', '小型', '安静', 1),
('查理', '比格混血', '3岁', '狗', '公', 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?auto=format&fit=crop&w=600&q=80', '聪明伶俐，嗅觉灵敏，是个小侦探', '健康', 1, 8, '《小侦探查理》查理以前是一只流浪狗，在街头流浪了很久。它特别聪明，总能找到藏起来的食物。现在在救助站，它成了大家的开心果。', '中型', '聪明', 1),
('米洛', '缅因猫', '4岁', '猫', '公', 'https://images.unsplash.com/photo-1513245543132-31f507417b26?auto=format&fit=crop&w=600&q=80', '体型巨大，性格温柔，是个温柔的巨人', '健康', 1, 12, '《温柔的巨人》米洛是被主人遗弃的，因为主人要搬家不能带它走。它虽然体型很大，但性格特别温柔，喜欢被人抚摸。', '大型', '温柔', 1),
('库珀', '柯基犬', '1岁', '狗', '公', 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=600&q=80', '短腿可爱，精力充沛，喜欢跑步', '健康', 1, 15, '《短腿小勇士》库珀是在宠物市场被救助的，当时它被关在狭小的笼子里。现在的库珀每天都在救助站的院子里快乐地奔跑，它的短腿跑得特别快！', '小型', '活泼', 1),
('黛西', '虎斑猫', '2个月', '猫', '母', 'https://images.unsplash.com/photo-1513360371669-4adf3dd7dff8?auto=format&fit=crop&w=600&q=80', '小猫一只，正在学习探索世界', '健康', 1, 6, '《小探险家黛西》黛西是一只刚出生不久的小猫，被发现时它和妈妈走散了。现在在救助站，它每天都在探索新事物，对什么都充满好奇。', '小型', '好奇', 1);
